name: Continous Integrations
on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Instalando Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Compilando
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build